### ISSUE TITLE
Getting error "unable to open X server"

### ISSUE THREAD

**Issue by prof-schnitzel** [single-spa/self-hosted-shared-dependencies#1]
I followed the instructions in the README.md and used the same content for the file shared-deps.conf.mjs. When I execute the command `npm run build-shared-deps` I get the following error:
```
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/358.
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/358.
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/358.
/node_modules/.bin/shared-deps: 5: /node_modules/.bin/shared-deps: Syntax error: "(" unexpected
```
I am using node with version 14.16.1.

You can also reproduce this issue by executing `docker run -it node:14 bash` and copying all scripts from README.md. Or by just cloning `polyglot-microfrontends/shared-dependencies` and running `npm run build`.

**Comment by jsmapr1** [comment]
These should be covered with PRs #2 and possibly #3. The key is adding `#!/usr/bin/env node` to `bin/self-hosted-shared-dependencies-cli.js` (worked for me at least).

**Comment by prof-schnitzel** [comment]
Just wanted to mention that it somehow works with pnpm. So there is only an issue when working with npm.

**Comment by joeldenning** [comment]
Makes sense - I generally use pnpm so that's why I didn't see it in my own testing. I've confirmed that it works using npm and version 1.0.3
