### ISSUE TITLE
Is there support for private packages from npm?

### ISSUE THREAD

**Issue by deviprsd** [single-spa/self-hosted-shared-dependencies#11]
Many organizations have private packages hosted on the public registry. I think npm-registry-fetch has a way to handle that. But I'm not sure if this package does so. It would be an easy addition with options, but if there is already a way what would it be?

**Comment by joeldenning** [comment]
Yes, see the `npmRegistry` option at https://github.com/single-spa/self-hosted-shared-dependencies#config-file

**Comment by deviprsd** [comment]
No, I meant to use a way to use token, username:password to access private packages from the public registry. Not every company goes about implementing a different registry.

**Comment by joeldenning** [comment]
Sorry I misread the issue. Reopening.

We use [npm-registry-fetch](https://github.com/npm/npm-registry-fetch) to load packages from the registry. It supports passing in username and password when calling the npm registry, so we should just add similar options to this repo and then pass them through to npm-registry-fetch.

**Comment by joeldenning** [comment]
This was released in https://github.com/single-spa/self-hosted-shared-dependencies/releases/tag/v1.3.0. See the new `registryFetchOptions` option for documentation - https://github.com/single-spa/self-hosted-shared-dependencies#config-file.
