### ISSUE TITLE
Default npm registry is always used

### ISSUE THREAD

**Issue by prof-schnitzel** [single-spa/self-hosted-shared-dependencies#4]
I am using a private registry which I enabled with the command `npm config set registry <url-to-registry>`. The self-hosted-shared-dependencies tool always seems to use `registry.npmjs.org` regardless of what is configured locally. Is it possible to make the tool respect the configured npm registry?

**Comment by prof-schnitzel** [comment]
Fixed by PR #8

**Comment by joeldenning** [comment]
👍🏿 agreed about why this is important, thanks for submitting the PR.
