### ISSUE TITLE
Not compatible with windows

### ISSUE THREAD

**Issue by prof-schnitzel** [single-spa/self-hosted-shared-dependencies#5]
The line `import(path.resolve(process.cwd(), configFile))` in `bin/self-hosted-shared-dependencies-cli.js` is not compatible with windows since you need correct URLs for the `import` command that start with `file://`.

**Comment by prof-schnitzel** [comment]
This should be fixed with PR #7

**Comment by joeldenning** [comment]
#7 is merged
