### ISSUE TITLE
Dependencies with a slash (foo/bar) do not work

### ISSUE THREAD

**Issue by prof-schnitzel** [single-spa/self-hosted-shared-dependencies#6]
When putting a package with a slash into the `shared-deps.conf.mjs` file (like `@company/my-lib`), the tool crashes with an exception, since it does not create subdirectories recursively. It needs to create first `@company` and then `my-lib` as a subdirectory, but this won't happen because the `recursive` option of the command `fs.mkdir` is not used.

**Comment by prof-schnitzel** [comment]
Fixed by PR #9

**Comment by joeldenning** [comment]
Released in https://github.com/single-spa/self-hosted-shared-dependencies/releases/tag/v1.0.4
